### ISSUE TITLE
C-99 required in IP2Loc_DBInterface.c

### ISSUE THREAD

**Issue by gvanem** [chrislim2888/IP2Location-C-Library#11]
This snippet at the end of `IP2Location_readFloat()` needs a C-99 compiler:
```c
  {
        fseek(handle, position-1, 0);
        size_t temp = fread(&ret, 4, 1, handle);
  }
```
`size_t` could easily be dropped as it is declared at the top.

**Comment by chrislim2888** [comment]
Sorry that I do not have windows environment to test on it. Perhaps, can you please send me the pull request of the fixes in windows? I will review and accept the pull if nothing break in linux.

**Comment by gvanem** [comment]
I'm not so much into *pull requests*. But below are patches all the issues I've found on Windows:
```diff
--- a/libIP2Location/IP2Loc_DBInterface.c 2017-08-22 10:23:46
+++ b/libIP2Location/IP2Loc_DBInterface.c 2017-08-23 16:48:31
@@ -366,7 +366,7 @@
     if (DB_access_type == IP2LOCATION_FILE_IO && handle != NULL)
     {
         fseek(handle, position-1, 0);
-        size_t temp = fread(&ret, 4, 1, handle);
+        temp = fread(&ret, 4, 1, handle);
     }
     else
     {
```
This fixes this C-99 issue.
The other issue with a missing `../config.h` and missing `PACKAGE_VERSION`, can be fixed by:
```diff
--- a/libIP2Location/IP2Location.c 2017-08-22 10:23:46
+++ b/libIP2Location/IP2Location.c 2017-08-24 09:43:18
@@ -33,7 +33,14 @@

 #include "IP2Location.h"
 #include "IP2Loc_DBInterface.h"
-#include "../config.h"
+
+#ifdef _WIN32
+  #define _STR2(x)  #x
+  #define _STR(x)  _STR2(x)
+  #define PACKAGE_VERSION  _STR(API_VERSION)
+#else
+  #include "../config.h"
+#endif

 typedef struct ipv_t
 {
```
And finally a IPv4/country test failure:
```diff
--- a/test/country_test_ipv4_data.txt 2017-08-22 10:23:46
+++ b/test/country_test_ipv4_data.txt 2017-08-22 12:57:48
@@ -2,7 +2,7 @@
 25.5.10.2	GB
 43.5.10.3	JP
 47.5.10.4	CA
-51.5.10.5	GB
+51.5.10.5	DE
 53.5.10.6	DE
 80.5.10.7	GB
 81.5.10.8	IL
```
Not so much to apply by hand I hope.

**Comment by gvanem** [comment]
There's still an error in `test/country_test_ipv4_data.txt`. According to my sources 51.5.10.5 is in Germany, e.g. from [C-ares's](https://github.com/c-ares/c-ares/) `acountry`:
```
acountry 51.5.10.5
Germany (de), number 276.
```
And [TCPIP-utils](https://www.tcpiputils.com/browse/ip-address/51.5.10.5) says the same.

**Comment by chrislim2888** [comment]
Yes, it is now relocated to DE. However, at the point of when this library was built, this IP was assigned to GB. And, the test IP addresses geolocation may change from time to time. 

Anyway the BIN in data folder given was pointed to GB, and this script is just a way for user to confirm if the library was successfully compiled. Shoudn't be issue for users to confirm the library functionalities.
