### ISSUE TITLE
Race in shared memory initialization

### ISSUE THREAD

**Issue by erankor** [chrislim2888/IP2Location-C-Library#13]
Hi,

First of all, thank you for this library!

I have several processes that query ip2location information and use IP2LOCATION_SHARED_MEMORY. The processes are started at the same time, and I noticed that when I restart the processes, I'm getting many ip2location errors.
I believe that what happens is that the first process creates the shared memory, and starts to load data into it. Before it finishes, a second processes tries to create the shared memory, sees that it already exists, and assumes that it's loaded, but it's not...
Is my understanding correct? are users of this library expected to synchronize calls to IP2Location_open_mem when using shared memory (didn't see this in the guide...)?

Thank you,

Eran

**Comment by erankor** [comment]
Just to update this thread that adding a lock around IP2Location_open_mem solved the problem. IMHO, worth adding a note about this in the guide.
On a slightly different subject - from what I see, the name of the shared memory object is hardcoded in the library. I think this can be problematic if I want to updated the ip2location database - it means I have to close the old database in all processes and only then open the new one. It would be better to add the option to pass the shared memory name as parameter, so that the application could use a new name for the new database and load it before all existing references are closed.

Thanks

Eran

**Comment by chrislim2888** [comment]
Thanks for pointing this out. You are right that you need to close the memory before updating a new one. At present, our library couldn't accept point to a mem location for location retrieval. Anyway, I will keep that in mind for future upgrade.
