### ISSUE TITLE
error during autoreconf with v8.0.7

### ISSUE THREAD

**Issue by rumahrumah** [chrislim2888/IP2Location-C-Library#19]
When I try to install the library v8.0.7, autoreconf fails with an error below

```
Makefile.am: error: required file './README' not found
autoreconf: automake failed with exit status: 1
```

Which does not appear in master branch.

Please consider releasing a new release v8.0.8 if this issue has been fixed.

**Comment by pbiering** [comment]
can confirm this issue

**Comment by ip2location** [comment]
The README file was missing in the package. Please use the latest release.
