### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by pbiering** [chrislim2888/IP2Location-C-Library#2]
According to changelog 8.0.3 is the last valid version but on https://www.ip2location.com/developers/c there is only a reference to "master". Please tag this release proper to make a consistent download later of 8.0.3 possible (and if possible/senseful, please tag releases < 8.0.1 also), currently, only 8.0.1 and 8.0.2 are tagged - thank you!

**Comment by chrislim2888** [comment]
Created a v8.0.3 tag
