### ISSUE TITLE
"make check" for IPv6 is broken

### ISSUE THREAD

**Issue by pbiering** [chrislim2888/IP2Location-C-Library#27]
looks like the IPv6 database created by the builtin "ip-country.pl" is no longer proper working, initialy "make check" segfaults, because NULL was returned on "get_all" -> imho this need some rework to support current status, which means one BIN file containing IPv4 and IPv6.

**Comment by ip2location** [comment]
Fixed in the latest [commit](https://github.com/chrislim2888/IP2Location-C-Library/commit/9a987645663b2e13191072df9d8866bf65bc85f5).
