### ISSUE TITLE
IP2Location-Lite-data RPM and "ip2locationlookup"

### ISSUE THREAD

**Issue by pbiering** [chrislim2888/IP2Location-C-Library#29]
this is related to https://github.com/chrislim2888/IP2Location-C-Library/issues/27

would it make sense to request similar to GeoIP-GeoLite-data an independent IP2Location-Lite-data RPM (dedicated package) -> should get regular updates

or should I create only a subpackage in the IP2Location RPM named IP2Location-data-sample which get only update from release to release (if ever) for initial testing.

Which leads me also to the request of "ip2locationlookup" (similar to geoiplookup), which uses the library and default or provided BIN files to check whether all is working fine.

**Comment by chrislim2888** [comment]
We prefer a subpackage that updated from release to release. Users should sign up the latest database in our web site https://lite.ip2location.com

**Comment by pbiering** [comment]
ok, will extend spec on FedoraBuildSystem next.

Can I expect the "ip2locationlookup" tool until 8.0.10 or will this arrive in a later stage?

Background: I plan not to push 8.0.9 to EL-stable but leave intermediate versions there for further testing and push then 8.0.10 which should be not so far away after all the PRs I've made (but wait at least until the data sub-RPM changes are submitted to upstream).

**Comment by chrislim2888** [comment]
Can you please release the version first? I think it may take a while before we can have the application ready.

**Comment by pbiering** [comment]
Sneak preview of more or less latest master + new subpackage "IP2Location-data-sample" now in fc34/rawhide, one can now check and test (rebuild of SRPMS on other favorite Fedora/EL version should also work):

https://koji.fedoraproject.org/koji/buildinfo?buildID=1608876

a change of the subpackage name can be still done

**Comment by chrislim2888** [comment]
No problem, we are good with the subpackage name.

**Comment by pbiering** [comment]
please check and test latest builds (8.0.9-9)

https://koji.fedoraproject.org/koji/packageinfo?packageID=32132

**Comment by chrislim2888** [comment]
We are going to build the command script. Can we use "ip2location" as the BIN name instead of "ip2locationlookup"? thanks.

**Comment by pbiering** [comment]
another option would be "ip2lookup", but I can also softlink to support multiple names

**Comment by pbiering** [comment]
8.0.9 has reached stable state for Fedora: https://src.fedoraproject.org/rpms/IP2Location - in 7 days also EL will follow

**Comment by ip2location** [comment]
We have developed ip2locationlookup and it's available at https://github.com/ip2location/ip2location-lookup/
