### ISSUE TITLE
Cross-licensing?

### ISSUE THREAD

**Issue by Ironholds** [chrislim2888/IP2Location-C-Library#3]
Heya,

So I'm looking to integrate ip2location support into rgeolocate - the standard R library for IP geolocation. The problem is that, due to other integrated code, it's an apache-licensed project, and ip2location's C lib is lGPL - and the two are [incompatible](https://www.apache.org/legal/resolved).

Is there any chance you'd be willing to dual-license this project under the Apache 2.0? That way I could integrate it (with appropriate licensing and credit to you).

**Comment by chrislim2888** [comment]
No problem. Please get the license text from Apache 2.0 and fill in the copyright as below
Copyright 2001-2016 IP2Location.com

I'm interesting to learn more about your project. Can you please let me know the link?

**Comment by Ironholds** [comment]
Sure! https://github.com/ironholds/rgeolocate
