### ISSUE TITLE
IP2Location_api_version_num changed to IP2Location_api_version_number

### ISSUE THREAD

**Issue by pbiering** [chrislim2888/IP2Location-C-Library#38]
it was a terrible idea to rename the api_version_number function - this totally kills backwards compatibilty for existing programs which already checking the version number (e.g. using dynload mechanism):

```
-unsigned long int IP2Location_api_version_number(void)
+unsigned long int IP2Location_api_version_num(void)
-unsigned long int IP2Location_api_version_number(void);
+unsigned long int IP2Location_api_version_num(void);
-	printf("IP2Location API version: %s (%lu)\n", IP2Location_api_version_string(), IP2Location_api_version_number());
+	printf("IP2Location API version: %s (%lu)\n", IP2Location_api_version_string(), IP2Location_api_version_num());
```

-> please re-add IP2Location_api_version_num and call then internally to IP2Location_api_version_number

BTW: such function should kept forever after introduced

**Comment by pbiering** [comment]
In addition please strongly avoid API *changes* in the future in minor releases, *add* is ok, but *replace* or *change* is not good in minor releases, this has a big chance to break any other software which will be take of of the library in Fedora/EPEL next -> please keep that in mind and maintain backwards compatibility all the time in minor releases. Otherwise I can't update the library in Fedora/EPEL further on to be on the safe side not breaking by accident existing software.

**Comment by ip2location** [comment]
As this library was developed by multiple authors, it was a mistake to simply standardize the functions at this time.

I have restored all the missing functions and it will be no future updates on these names to prevent further issues.
