### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Dilvish5** [chrislim2888/IP2Location-C-Library#39]
Hello

I would like to report an issue that seems to cause segmentation fault in apache  (with mod_ip2location) and libIP2Location
From the coredump i extracted this: IP2Location_free_record (libIP2Location.so.1)#012#6  0x00007fc39bbbdde0 ip2location_post_read_request (mod_ip2location.so)#012#7

I've tried to compile the latest version (8cc0f69), but the issue seems to persist.

Thank you very much for all your work!

**Comment by ip2location** [comment]
Thanks for reporting, let me investigate the issue.

**Comment by ip2location** [comment]
Using the last version should install "libIP2Location.so.2" instead of "libIP2Location.so.1". Can you confirmed that you have compiled with the latest version?

**Comment by Dilvish5** [comment]
Yes, i just renamed the file  to .1 to be sure it's using it instead of the old one.

**Comment by remicollet** [comment]
> Yes, i just renamed the file to .1 to be sure it's using it instead of the old one.

This obviously cannot work....
this suffix is direftly related to the ABI... different number means incompatible change.

You need to rebuild mod_ip2location

**Comment by Dilvish5** [comment]
You're right, i've rebuilt mod_ip2location today and could not detect any issues. Thank you!!!
