### ISSUE TITLE
Shared-memory name

### ISSUE THREAD

**Issue by gvanem** [chrislim2888/IP2Location-C-Library#44]
The shared-memory object under Windows is a bit strangely named:
```
\Sessions\1\BaseNamedObjects\/IP2location_Shm
```
since `IP2Location.h` has a `#define IP2LOCATION_SHM "/IP2location_Shm"`. 

Maybe it would be best to give `CreateFileMapping()` a suitable name depending on if `UNICODE` is defined etc?

**Comment by ip2location** [comment]
Can you create a pull request for this change?

**Comment by gvanem** [comment]
The PR was merged. Hence closing.
