### ISSUE TITLE
UNICODE support

### ISSUE THREAD

**Issue by Mecanik** [chrislim2888/IP2Location-C-Library#51]
This is more like a suggestion, but you could add UNICODE support as well? So people with UNICODE apps do not need to convert from ASCII...

You could also add lookup based on IN_ADDR instead of formatted string.

Again, these are just suggestions but they would be very nice to have.

**Comment by ip2location** [comment]
You will need to convert the values into Unicode manually.

If you have a better idea with IN_ADDR, you can send us a pull request,
