### ISSUE TITLE
Inconsistencies and error using ASN database

### ISSUE THREAD

**Issue by Mecanik** [chrislim2888/IP2Location-C-Library#52]
Hi,

I found some issues in my attempt of using the IP2Location™ LITE IP-ASN Database. Please see below:

- It is impossible to download the BIN format; the website always gives you the CSV format
- It is impossible to open and load 2 databases at the same time (for example IP2LOCATION-LITE-DB3.BIN and IP2LOCATION-LITE-ASN.BIN); now I`m not sure if this is due to the fact that I converted the ASN CSV to BIN format using your script...?
- It is unclear which record is the ASN; the ASN CSV contains the number + name, yet there is no function to retrieve it. There is IP2Location_get_isp(), however this returns what exactly? (cannot test since I cannot open the ASN DB)

Please try to answer my questions/issues.

Thanks

**Comment by pbiering** [comment]
>     * It is impossible to open and load 2 databases at the same time (for example IP2LOCATION-LITE-DB3.BIN and IP2LOCATION-LITE-ASN.BIN); now I`m not sure if this is due to the fact that I converted the ASN CSV to BIN format using your script...?

By nature one can only load one BIN file at one time if no sophisticated surrounding code is used.

>     * It is unclear which record is the ASN; the ASN CSV contains the number + name, yet there is no function to retrieve it. There is IP2Location_get_isp(), however this returns what exactly? (cannot test since I cannot open the ASN DB)

"get_isp" is unrelated to ASN, potentially a code lookup in the related wrapper library of "ipv6calc" would provide you some details how to use: https://github.com/pbiering/ipv6calc/tree/master/databases/lib

**Comment by ip2location** [comment]
The ASN database is only available in CSV format. You cannot convert it into BIN format and query with this library.
