### ISSUE TITLE
INSTALL instructions outdated

### ISSUE THREAD

**Issue by pbiering** [chrislim2888/IP2Location-C-Library#54]
https://github.com/chrislim2888/IP2Location-C-Library/blob/master/INSTALL

requires update, especially after the cleanup by https://github.com/chrislim2888/IP2Location-C-Library/commit/876079ad2ed18106593fa332efa8bad0f2f0f385

_Briefly, the shell command './configure && make && make install'_
...

_1. 'cd' to the directory containing the package's source code and type
     './configure' to configure the package for your system._

requires `autoreconf -fiv` in advance, otherwise no "configure" is available and "bootstrap" and preexisting files were removed on cleanup

**Comment by ip2location** [comment]
Updated.
