### ISSUE TITLE
[8.4.0] failed test

### ISSUE THREAD

**Issue by jorjick** [chrislim2888/IP2Location-C-Library#55]
8.4.0 Still failed tests.
ip-country.pl set 29,30 byte to 0 therefore this test fail

	if (handler->product_code == 1) {
	} else {
		if (handler->database_year <= 20 && handler->product_code == 0) {
		} else {
			printf(INVALID_BIN_DATABASE);
			return NULL;
		}
	}

IP2Loc 8.4.0: test/test-suite.log
\=======================================

\# TOTAL: 1
\# PASS:  0
\# SKIP:  0
\# XFAIL: 0
\# FAIL:  1
\# XPASS: 0
\# ERROR: 0

.. contents:: :depth: 2

FAIL: test-IP2Location
\======================

IP2Location library error in opening database ../data/IP-COUNTRY.BIN.
IP2Location API version: 8.4.0 (80400)
Please install the database in correct path.
FAIL test-IP2Location (exit status: 255)

**Comment by ip2location** [comment]
Get it fixed in 8.4.1.
