### ISSUE TITLE
master/8.6.1(e49e2f3) - Fail to build on Debian 12

### ISSUE THREAD

**Issue by gkapad** [chrislim2888/IP2Location-C-Library#65]
- grep PRETTY /etc/os-release 
`PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"`

- uname -a
`Linux router 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-2 (2023-07-27) x86_64 GNU/Linux`

- build
```
- git pull
- autoreconf -i -v --force
- configure
- make

-
```
24.151.2337/07
router@pts/8/root   github.com/chrislim2888/IP2Location-C-Library  ✅ master/8.6.1(e49e2f3)
# /servers/.builds/nginx/IP2Location-C-Library.git
make
make  all-recursive
make[1]: Entering directory '/mnt/Banker/VDISK/.builds/nginx/IP2Location-C-Library.git'
Making all in libIP2Location
make[2]: Entering directory '/mnt/Banker/VDISK/.builds/nginx/IP2Location-C-Library.git/libIP2Location'
depbase=`echo IP2Location.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I. -pipe -D _GNU_SOURCE -D _GNU_SOURCE -I/usr/include -Wno-unused-result  -g -O2 -lrt -MT IP2Location.lo -MD -MP -MF $depbase.Tpo -c -o IP2Location.lo IP2Location.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -pipe -D _GNU_SOURCE -D _GNU_SOURCE -I/usr/include -Wno-unused-result -g -O2 -lrt -MT IP2Location.lo -MD -MP -MF .deps/IP2Location.Tpo -c IP2Location.c  -fPIC -DPIC -o .libs/IP2Location.o
IP2Location.c:79:12: error: conflicting types for 'lookup_mode'; have 'int'
   79 | extern int lookup_mode;
      |            ^~~~~~~~~~~
IP2Location.c:76:37: note: previous definition of 'lookup_mode' with type 'enum IP2Location_lookup_mode'
   76 | static enum IP2Location_lookup_mode lookup_mode = IP2LOCATION_FILE_IO; /* Set default lookup mode as File I/O */
      |                                     ^~~~~~~~~~~
make[2]: *** [Makefile:444: IP2Location.lo] Error 1
make[2]: Leaving directory '/mnt/Banker/VDISK/.builds/nginx/IP2Location-C-Library.git/libIP2Location'
make[1]: *** [Makefile:656: all-recursive] Error 1
make[1]: Leaving directory '/mnt/Banker/VDISK/.builds/nginx/IP2Location-C-Library.git'
make: *** [Makefile:412: all] Error 2
```

**Comment by ip2location** [comment]
It's fixed. Please grab the latest codes.
