### ISSUE TITLE
SIGBUS error on mmap

### ISSUE THREAD

**Issue by vincent-richard** [chrislim2888/IP2Location-C-Library#7]
Hello!

I encountered an issue when using IP2Location with IP2LOCATION_SHARED_MEMORY access type, and reloading the database regularly, within the same running process.

So, the process simply calls IP2Location_DB_close() and IP2Location_delete_shm(), then IP2Location_open() and IP2Location_open_mem(IP2LOCATION_SHARED_MEMORY) again.

Sometimes, the process crashes with SIGBUS when fread()ing the data into the mmap()ed shared memory segment. This is caused by the process eventually running out of memory because of an issue in the IP2Location_DB_close() function: the file handle is fclose()d before we call fstat() on it, so munmap() is called with the wrong size (so, not all memory is freed):

```
int32_t IP2Location_DB_close(FILE *filehandle)
{
    struct stat statbuf;
    if ( filehandle != NULL )
        fclose(filehandle);            <---- filehandle closed here
    if ( DB_access_type == IP2LOCATION_CACHE_MEMORY )
    {
        if( cache_shm_ptr != NULL )
            free(cache_shm_ptr);
    }
    else if ( DB_access_type == IP2LOCATION_SHARED_MEMORY )
    {
        if( cache_shm_ptr != NULL )
        {
#ifndef	WIN32
            if(fstat(fileno(filehandle), &statbuf) == 0)      <---- filehandle used here
            {
                munmap(cache_shm_ptr, statbuf.st_size);
            }
            close(shm_fd);
#else
#ifdef WIN32
            UnmapViewOfFile(cache_shm_ptr);
            CloseHandle(shm_fd);
#endif
#endif
        }
    }
    DB_access_type = IP2LOCATION_FILE_IO;
    return 0;
}
```

The fix is to put the following block:

```
    if ( filehandle != NULL )
        fclose(filehandle);
```

at the end of the IP2Location_DB_close() function.

**Comment by chrislim2888** [comment]
Thanks for pointing this out. It has been fixed.
